spring:
  application:
    name: ms-users
  security:
    oauth2:
      #      resourceserver:
      #        jwt:
      #          issuer-uri: http://localhost:8080/realms/bills
      client:
        registration:
          keycloak:
            client-id: user-client-credentials
            client-secret: GfqvsiQWLId1wgFOwSVgDtZt6GoywAMZ
            authorization-grant-type: client_credentials
        #            provider: keycloak
        provider:
          keycloak:
            #            issuer-uri: http://localhost:8080/realms/bills
            tokenUri: http://localhost:8080/realms/bills/protocol/openid-connect/token


eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8081
