INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE)
VALUES (RANDOM_UUID(), 'Jhon', 'courses/Java', 500);
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE)
VALUES (RANDOM_UUID(), 'Michael', 'courses/Java', 500);
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE)
VALUES (RANDOM_UUID(), 'Peter', 'courses/Java', 500);
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE)
VALUES (RANDOM_UUID(), 'Sebastian', 'courses/Java', 500);
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE)
VALUES (RANDOM_UUID(), 'Aaron','courses/Java', 500);
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE)
VALUES (RANDOM_UUID(), 'William', 'courses/Java', 500);
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE)
VALUES (RANDOM_UUID(),'61b95f0c-939e-4496-9070-811801472db7', 'courses/Java', 500);

